[package]
name = "burning"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.9"
actix-sse = "0.1.0"
actix-web = "4.12.1"
futures-util = "0.3.31"
notify = "8.2.0"
tokio = { version = "1.48.0", features = ["sync"] }
tokio-stream = "0.1.17"
